version: '3.9'

services:
  log-target-generator:
    image: registry.gitlab.com/dfinity-lab/core/release/nikola-milosa/log-vector-config-generator:2.0
    network_mode: host
    hostname: 127.0.0.1
    command: ["--targets-dir", "/tmp/discovery_wd", "--generation-dir", "/generated-config", "--nns-url", "http://[2401:3f00:1000:23:6801:11ff:fec4:706d]:8080", "--filter-node-id-regex", "dndht-2fce7-aze7e-coa4j-yvyuw-ut4hw-gn5dj-xvxox-whdhg-txikb-yae", "--batch-size", "100"]
    container_name: "log-generator"
    volumes:
      - ./vector:/generated-config
      - ./discovery_wd:/tmp/discovery_wd
    depends_on:
      - loki

  vector:
    image: registry.gitlab.com/dfinity-lab/core/release/nikola-milosa/vector-modified:2.0
    network_mode: host
    hostname: 127.0.0.1
    command: ["--config-dir", "/etc/vector/"]
    restart: always
    environment:
      VECTOR_WATCH_CONFIG: "true"
    container_name: vector
    volumes:
      - ./vector:/etc/vector
      - ./logs:/logs

  loki:
    image: grafana/loki
    container_name: "loki"
    ports:
      - 3100:3100
    volumes:
      - loki:/loki
    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    container_name: "grafana"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
    volumes:
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning

volumes:
  loki: