version: '3.9'

services:

  vector:
    image: registry.gitlab.com/dfinity-lab/core/release/nikola-milosa/vector-modified:sns-1.2
    network_mode: host
    hostname: 127.0.0.1
    command: ["--config-dir", "/etc/vector/"]
    restart: always
    environment:
      VECTOR_WATCH_CONFIG: "true"
    container_name: vector
    volumes:
      - ./vector:/etc/vector
      - ./logs:/logs

  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  
  kibana:
    image: kibana:7.4.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch