# The lifeline is a motoko canister.
#
# This Cargo file exists so that we can invoke `moc`, the motoko compiler, at rust compile time.
# src/lib.rs is a rust wrapper library that exposes the lifetime.wasm as a constant, for testing.

[package]
name = "lifeline"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "lifeline"
path = "src/main.rs"

[build-dependencies]
ic-nns-constants = { path = "../../constants" }
ic-base-types = { path = "../../../types/base_types" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
wasmprinter = "0.2.45"
candid = "0.8.1"
dfn_candid = {path="../../../rust_canisters/dfn_candid"}
ic-ic00-types = {path="../../../types/ic00_types"}
ic-nns-common ={path="../../common"}
ic-nervous-system-root = { path="../../../nervous_system/root" }
ic-nns-test-utils = { path = "../../../nns/test_utils" }
