[sources.source_demo-logs]
type = "demo_logs"
format = "json"

[transforms.transform_demo-logs]
type = "remap"
inputs = [ "source_demo-logs" ]
source = ".place_holder = true"

[transforms.total_filter]
type = "filter"
inputs = ["transform_*"]
condition = ".place_holder == null"

[transforms.elastic_timestamp]
type = "remap"
inputs = ["total_filter"]
source = """
.timestamp = to_timestamp!(del(.timestamp), "nanoseconds")
"""

[sinks.out_elastic]
type = "elasticsearch"
inputs = ["elastic_timestamp"]
compression = "none"
endpoint = "http://elasticsearch.dfinity.systems"
api_version = "v7"
