[sources.logs_from_canister_5s2ji]
type = "sns_canister"
endpoint = "https://5s2ji-faaaa-aaaaa-qaaaq-cai.raw.medium09.testnet.dfinity.network"
data_dir = "logs"

[sources.logs_from_canister_5j7vn]
type = "sns_canister"
endpoint = "https://5j7vn-7yaaa-aaaaa-qaaca-cai.raw.medium09.testnet.dfinity.network"
data_dir = "logs"

[sources.logs_from_canister_54yea]
type = "sns_canister"
endpoint = "https://54yea-6qaaa-aaaaa-qaabq-cai.raw.medium09.testnet.dfinity.network"
data_dir = "logs"

[sources.logs_from_canister_5o6tz]
type = "sns_canister"
endpoint = "https://5o6tz-saaaa-aaaaa-qaacq-cai.raw.medium09.testnet.dfinity.network"
data_dir = "logs"

[sources.logs_from_canister_53zcu]
type = "sns_canister"
endpoint = "https://53zcu-tiaaa-aaaaa-qaaba-cai.raw.medium09.testnet.dfinity.network"
data_dir = "logs"

[sinks.out_logs]
type = "file"
inputs = ["logs_from_canister*"]
compression = "none"
path = "logs/logs.log"
    [sinks.out_logs.encoding]
    codec = "json"

[sinks.out_loki]
type = "loki"
inputs = ["logs_from_canister*"]
compression = "none"
endpoint = "http://localhost:3100"
remove_label_fields = true
    [sinks.out_loki.labels]
    file = "{{ file }}"
    line = "{{ line }}"
    severity = "{{ severity }}"
    [sinks.out_loki.encoding]
    codec = "json"

[sinks.out_elastic]
type = "elasticsearch"
inputs = ["logs_from_canister*"]
compression = "none"
endpoint = "http://localhost:9200"
mode = "bulk"