[transforms.elastic_timestamp]
type = "remap"
inputs = ["transform_*"]
source = """
.timestamp = to_timestamp!(del(.timestamp), "nanoseconds")
"""

[sinks.out_elastic]
type = "elasticsearch"
inputs = ["elastic_timestamp"]
compression = "none"
endpoint = "http://localhost:9200"
api_version = "v7"
mode = "bulk"
    [sinks.out_elastic.bulk]
    index = "sns-canister-logs-%Y-%m-%d"
